### ISSUE TITLE
Text Area

### ISSUE THREAD

**Issue by TomLingham** [iag-abd/macgooey#3]
We're going to need a text area / multiline text input component.

**Comment by thachling** [comment]
oh me me

**Comment by TomLingham** [comment]
I think @unerh was going to grab this one. Can you grab #2?

**Comment by thachling** [comment]
only if you give me some chocolate

**Comment by TomLingham** [comment]
Gah!! Fine.... Better be a really good Toggle component though

**Comment by thachling** [comment]
it will be of equal quality to the chocolate
